# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "bixalcom:http"
  tls:
    # https://docs.platform.sh/define-routes/https.html#stricttransportsecurity
    strict_transport_security:
      # This is one year, can't change.
      enabled: true
      include_subdomains: false
      preload: false
  cache:
    enabled: true

    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
