# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

database:
  type: mariadb:10.3
  disk: 2048

cache:
  type: redis:6.2

searchsolr:
  # Version 8 is not supported right now, 7.7 is supported by both lando and platform.
  type: solr:7.7
  disk: 1024
  configuration:
    cores:
      # Might require finishing configuring solr via https://docs.platform.sh/guides/drupal9/solr.html#6-export-and-modify-configuration.
      maincore: { }
    endpoints:
      main:
        core: maincore
